#!/bin/bash
rm -rf /data 2>/dev/null; mkdir -p /data/data 2>/dev/null; mkdir -p /data/log 2>/dev/null ; cp sql /data/data/sql
MIDATA="/data/data"
MILOG="/data/log"
CONTENEDOR_DATA="/var/opt/mssql/data"
CONTENEDOR_LOG="/var/opt/mssql/log"
CONTENEDOR_SEC="/var/opt/mssql/secrets"


docker run --rm \
	-h sqlserver \
	-p 1433:1433 \
	--name sqlserver \
	-d -e 'ACCEPT_EULA=Y' \
	-e 'SA_PASSWORD=test$$S8' \
	-w $CONTENEDOR_DATA \
	-v "$MILOG":$CONTENEDOR_SEC \
	-v "$MILOG":"$CONTENEDOR_LOG" \
	-v "$MIDATA":"$CONTENEDOR_DATA" \
	microsoft/mssql-server-linux:2017-latest

sleep 1
echo "Password SQL Server"
docker exec -it sqlserver \
	/opt/mssql-tools/bin/sqlcmd \
	-i $CONTENEDOR_DATA/sql \
	-o $CONTENEDOR_DATA/out \
	-S localhost -U SA


echo ''
echo 'docker exec -it sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA'
echo ''
exit 0;
